/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    Badge: typeof import('./src/components/ui/badge/Badge.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    DatasetCard: typeof import('./src/components/datasets/DatasetCard.vue')['default']
    DatasetCardSkeleton: typeof import('./src/components/skeletons/DatasetCardSkeleton.vue')['default']
    DatasetDetailSkeleton: typeof import('./src/components/skeletons/DatasetDetailSkeleton.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    Label: typeof import('./src/components/ui/label/Label.vue')['default']
    Navbar: typeof import('./src/components/layout/Navbar.vue')['default']
    PageHeader: typeof import('./src/components/layout/PageHeader.vue')['default']
    PageSection: typeof import('./src/components/shared/PageSection.vue')['default']
    PanSharpeningDatasetShow: typeof import('./src/components/datasets/PanSharpeningDatasetShow.vue')['default']
    Progress: typeof import('./src/components/ui/progress/Progress.vue')['default']
    ProjectCard: typeof import('./src/components/projects/ProjectCard.vue')['default']
    ProjectCardSkeleton: typeof import('./src/components/skeletons/ProjectCardSkeleton.vue')['default']
    ProjectDetailSkeleton: typeof import('./src/components/skeletons/ProjectDetailSkeleton.vue')['default']
    ProjectList: typeof import('./src/components/projects/ProjectList.vue')['default']
    ProjectSearch: typeof import('./src/components/projects/ProjectSearch.vue')['default']
    ResearchAreaCard: typeof import('./src/components/shared/ResearchAreaCard.vue')['default']
    ResearchAreasSection: typeof import('./src/components/sections/ResearchAreasSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchDialog: typeof import('./src/components/search/SearchDialog.vue')['default']
    SegDatasetShow: typeof import('./src/components/datasets/SegDatasetShow.vue')['default']
    SegmentationDemo: typeof import('./src/components/demos/SegmentationDemo.vue')['default']
    Sheet: typeof import('./src/components/ui/sheet/Sheet.vue')['default']
    SheetClose: typeof import('./src/components/ui/sheet/SheetClose.vue')['default']
    SheetContent: typeof import('./src/components/ui/sheet/SheetContent.vue')['default']
    SheetDescription: typeof import('./src/components/ui/sheet/SheetDescription.vue')['default']
    SheetFooter: typeof import('./src/components/ui/sheet/SheetFooter.vue')['default']
    SheetHeader: typeof import('./src/components/ui/sheet/SheetHeader.vue')['default']
    SheetTitle: typeof import('./src/components/ui/sheet/SheetTitle.vue')['default']
    SheetTrigger: typeof import('./src/components/ui/sheet/SheetTrigger.vue')['default']
    Textarea: typeof import('./src/components/ui/textarea/Textarea.vue')['default']
    ThemeToggle: typeof import('./src/components/shared/ThemeToggle.vue')['default']
    Toast: typeof import('./src/components/ui/toast/Toast.vue')['default']
    ToastAction: typeof import('./src/components/ui/toast/ToastAction.vue')['default']
    ToastClose: typeof import('./src/components/ui/toast/ToastClose.vue')['default']
    ToastDescription: typeof import('./src/components/ui/toast/ToastDescription.vue')['default']
    Toaster: typeof import('./src/components/ui/toast/Toaster.vue')['default']
    ToastProvider: typeof import('./src/components/ui/toast/ToastProvider.vue')['default']
    ToastTitle: typeof import('./src/components/ui/toast/ToastTitle.vue')['default']
    ToastViewport: typeof import('./src/components/ui/toast/ToastViewport.vue')['default']
  }
}
